#![allow(dead_code)]

pub const FREEZE_LATITUDE_LONGITUDE_TOGGLE: &'static str = "FREEZE_LATITUDE_LONGITUDE_TOGGLE";
pub const FREEZE_LATITUDE_LONGITUDE_SET: &'static str = "FREEZE_LATITUDE_LONGITUDE_SET";
pub const FREEZE_ALTITUDE_TOGGLE: &'static str = "FREEZE_ALTITUDE_TOGGLE";
pub const FREEZE_ALTITUDE_SET: &'static str = "FREEZE_ALTITUDE_SET";
pub const FREEZE_ATTITUDE_TOGGLE: &'static str = "FREEZE_ATTITUDE_TOGGLE";
pub const FREEZE_ATTITUDE_SET: &'static str = "FREEZE_ATTITUDE_SET";
