#![allow(dead_code)]

pub const POINT_OF_INTEREST_TOGGLE_POINTER: &'static str = "POINT_OF_INTEREST_TOGGLE_POINTER";
pub const POINT_OF_INTEREST_CYCLE_PREVIOUS: &'static str = "POINT_OF_INTEREST_CYCLE_PREVIOUS";
pub const POINT_OF_INTEREST_CYCLE_NEXT: &'static str = "POINT_OF_INTEREST_CYCLE_NEXT";
