#![allow(dead_code)]

pub const LOW_HEIGHT_WARNING_GAUGE_WILL_SET: &'static str = "LOW_HEIGHT_WARNING_GAUGE_WILL_SET";
pub const LOW_HIGHT_WARNING_GAUGE_WILL_SET: &'static str = "LOW_HIGHT_WARNING_GAUGE_WILL_SET";
pub const LOW_HEIGHT_WARNING_SET: &'static str = "LOW_HEIGHT_WARNING_SET";
pub const LOW_HIGHT_WARNING_SET: &'static str = "LOW_HIGHT_WARNING_SET";
pub const TOGGLE_ELECTRICAL_FAILURE: &'static str = "TOGGLE_ELECTRICAL_FAILURE";
pub const TOGGLE_ENGINE1_FAILURE: &'static str = "TOGGLE_ENGINE1_FAILURE";
pub const TOGGLE_ENGINE2_FAILURE: &'static str = "TOGGLE_ENGINE2_FAILURE";
pub const TOGGLE_ENGINE3_FAILURE: &'static str = "TOGGLE_ENGINE3_FAILURE";
pub const TOGGLE_ENGINE4_FAILURE: &'static str = "TOGGLE_ENGINE4_FAILURE";
pub const TOGGLE_HYDRAULIC_FAILURE: &'static str = "TOGGLE_HYDRAULIC_FAILURE";
pub const TOGGLE_LEFT_BRAKE_FAILURE: &'static str = "TOGGLE_LEFT_BRAKE_FAILURE";
pub const TOGGLE_PITOT_BLOCKAGE: &'static str = "TOGGLE_PITOT_BLOCKAGE";
pub const TOGGLE_RIGHT_BRAKE_FAILURE: &'static str = "TOGGLE_RIGHT_BRAKE_FAILURE";
pub const TOGGLE_STATIC_PORT_BLOCKAGE: &'static str = "TOGGLE_STATIC_PORT_BLOCKAGE";
pub const TOGGLE_TOTAL_BRAKE_FAILURE: &'static str = "TOGGLE_TOTAL_BRAKE_FAILURE";
pub const TOGGLE_VACUUM_FAILURE: &'static str = "TOGGLE_VACUUM_FAILURE";
