#![allow(dead_code)]

pub const PRESSURIZATION_PRESSURE_ALT_INC: &'static str = "PRESSURIZATION_PRESSURE_ALT_INC";
pub const PRESSURIZATION_PRESSURE_ALT_DEC: &'static str = "PRESSURIZATION_PRESSURE_ALT_DEC";
pub const PRESSURIZATION_CLIMB_RATE_INC: &'static str = "PRESSURIZATION_CLIMB_RATE_INC";
pub const PRESSURIZATION_CLIMB_RATE_DEC: &'static str = "PRESSURIZATION_CLIMB_RATE_DEC";
pub const PRESSURIZATION_PRESSURE_DUMP_SWTICH: &'static str = "PRESSURIZATION_PRESSURE_DUMP_SWTICH";
