#![allow(dead_code)]

pub const FUELSYSTEM_JUNCTION_SET: &'static str = "FUELSYSTEM_JUNCTION_SET";
pub const FUELSYSTEM_PUMP_OFF: &'static str = "FUELSYSTEM_PUMP_OFF";
pub const FUELSYSTEM_PUMP_ON: &'static str = "FUELSYSTEM_PUMP_ON";
pub const FUELSYSTEM_PUMP_SET: &'static str = "FUELSYSTEM_PUMP_SET";
pub const FUELSYSTEM_PUMP_TOGGLE: &'static str = "FUELSYSTEM_PUMP_TOGGLE";
pub const FUELSYSTEM_TRIGGER_OFF: &'static str = "FUELSYSTEM_TRIGGER_OFF";
pub const FUELSYSTEM_TRIGGER_ON: &'static str = "FUELSYSTEM_TRIGGER_ON";
pub const FUELSYSTEM_TRIGGER_SET: &'static str = "FUELSYSTEM_TRIGGER_SET";
pub const FUELSYSTEM_TRIGGER_TOGGLE: &'static str = "FUELSYSTEM_TRIGGER_TOGGLE";
pub const FUELSYSTEM_VALVE_CLOSE: &'static str = "FUELSYSTEM_VALVE_CLOSE";
pub const FUELSYSTEM_VALVE_OPEN: &'static str = "FUELSYSTEM_VALVE_OPEN";
pub const FUELSYSTEM_VALVE_SET: &'static str = "FUELSYSTEM_VALVE_SET";
pub const FUELSYSTEM_VALVE_TOGGLE: &'static str = "FUELSYSTEM_VALVE_TOGGLE";
