#![allow(dead_code)]

pub const ADD_FUEL_QUANTITY: &'static str = "ADD_FUEL_QUANTITY";
pub const ELECT_FUEL_PUMP1_SET: &'static str = "ELECT_FUEL_PUMP1_SET";
pub const ELECT_FUEL_PUMP2_SET: &'static str = "ELECT_FUEL_PUMP2_SET";
pub const ELECT_FUEL_PUMP3_SET: &'static str = "ELECT_FUEL_PUMP3_SET";
pub const ELECT_FUEL_PUMP4_SET: &'static str = "ELECT_FUEL_PUMP4_SET";
pub const ENGINE_FUELFLOW_BUG_POSITION1: &'static str = "ENGINE_FUELFLOW_BUG_POSITION1";
pub const ENGINE_FUELFLOW_BUG_POSITION2: &'static str = "ENGINE_FUELFLOW_BUG_POSITION2";
pub const ENGINE_FUELFLOW_BUG_POSITION3: &'static str = "ENGINE_FUELFLOW_BUG_POSITION3";
pub const ENGINE_FUELFLOW_BUG_POSITION4: &'static str = "ENGINE_FUELFLOW_BUG_POSITION4";
pub const FUEL_DUMP_SWITCH_SET: &'static str = "FUEL_DUMP_SWITCH_SET";
pub const FUEL_DUMP_TOGGLE: &'static str = "FUEL_DUMP_TOGGLE";
pub const MANUAL_FUEL_PRESSURE_PUMP: &'static str = "MANUAL_FUEL_PRESSURE_PUMP";
pub const MANUAL_FUEL_PRESSURE_PUMP_SET: &'static str = "MANUAL_FUEL_PRESSURE_PUMP_SET";
pub const MANUAL_FUEL_TRANSFER: &'static str = "MANUAL_FUEL_TRANSFER";
pub const RELEASE_DROP_TANK_ALL: &'static str = "RELEASE_DROP_TANK_ALL";
pub const RELEASE_DROP_TANK_1: &'static str = "RELEASE_DROP_TANK_1";
pub const RELEASE_DROP_TANK_2: &'static str = "RELEASE_DROP_TANK_2";
pub const REPAIR_AND_REFUEL: &'static str = "REPAIR_AND_REFUEL";
pub const REQUEST_FUEL_KEY: &'static str = "REQUEST_FUEL_KEY";
pub const ANTIDETONATION_TANK_VALVE_TOGGLE: &'static str = "ANTIDETONATION_TANK_VALVE_TOGGLE";
pub const NITROUS_TANK_VALVE_TOGGLE: &'static str = "NITROUS_TANK_VALVE_TOGGLE";
