pub mod cross_feed;
pub mod fuel_selector;
pub mod fuel_system;
pub mod fuel_transfer;
pub mod miscellanous;

#[allow(dead_code)]
#[allow(non_camel_case_types)]
pub enum FuelSelectorCodes {
    FUEL_TANK_SELECTOR_OFF,
    FUEL_TANK_SELECTOR_ALL,
    FUEL_TANK_SELECTOR_LEFT,
    FUEL_TANK_SELECTOR_RIGHT,
    FUEL_TANK_SELECTOR_LEFT_AUX,
    FUEL_TANK_SELECTOR_RIGHT_AUX,
    FUEL_TANK_SELECTOR_CENTER,
    FUEL_TANK_SELECTOR_CENTER2,
    FUEL_TANK_SELECTOR_CENTER3,
    FUEL_TANK_SELECTOR_EXTERNAL1,
    FUEL_TANK_SELECTOR_EXTERNAL2,
    FUEL_TANK_SELECTOR_RIGHT_TIP,
    FUEL_TANK_SELECTOR_LEFT_TIP,
    FUEL_TANK_SELECTOR_CROSSFEED,
    FUEL_TANK_SELECTOR_CROSSFEED_L2R,
    FUEL_TANK_SELECTOR_CROSSFEED_R2L,
    FUEL_TANK_SELECTOR_BOTH,
    FUEL_TANK_SELECTOR_EXTERNAL_ALL,
    FUEL_TANK_SELECTOR_ISOLATE,
}
