#![allow(dead_code)]

pub const ELECTRICAL_BUS_BREAKER_TOGGLE: &'static str = "ELECTRICAL_BUS_BREAKER_TOGGLE";
pub const ELECTRICAL_BUS_TO_ALTERNATOR_CONNECTION_TOGGLE: &'static str =
    "ELECTRICAL_BUS_TO_ALTERNATOR_CONNECTION_TOGGLE";
pub const ELECTRICAL_BUS_TO_BATTERY_CONNECTION_TOGGLE: &'static str =
    "ELECTRICAL_BUS_TO_BATTERY_CONNECTION_TOGGLE";
pub const ELECTRICAL_BUS_TO_BUS_CONNECTION_TOGGLE: &'static str =
    "ELECTRICAL_BUS_TO_BUS_CONNECTION_TOGGLE";
pub const ELECTRICAL_BUS_TO_CIRCUIT_CONNECTION_TOGGLE: &'static str =
    "ELECTRICAL_BUS_TO_CIRCUIT_CONNECTION_TOGGLE";
pub const ELECTRICAL_BUS_TO_EXTERNAL_POWER_CONNECTION_TOGGLE: &'static str =
    "ELECTRICAL_BUS_TO_EXTERNAL_POWER_CONNECTION_TOGGLE";
pub const ELECTRICAL_CIRCUIT_BREAKER_TOGGLE: &'static str = "ELECTRICAL_CIRCUIT_BREAKER_TOGGLE";
pub const ELECTRICAL_CIRCUIT_POWER_SETTING_SET: &'static str =
    "ELECTRICAL_CIRCUIT_POWER_SETTING_SET";
pub const ELECTRICAL_CIRCUIT_TOGGLE: &'static str = "ELECTRICAL_CIRCUIT_TOGGLE";
pub const ELECTRICAL_EXECUTE_PROCEDURE: &'static str = "ELECTRICAL_EXECUTE_PROCEDURE";
pub const ELECTRICAL_EXTERNAL_POWER_BREAKER_TOGGLE: &'static str =
    "ELECTRICAL_EXTERNAL_POWER_BREAKER_TOGGLE";
pub const PANEL_LIGHTS_POWER_SETTING_SET: &'static str = "PANEL_LIGHTS_POWER_SETTING_SET";
pub const CABIN_LIGHTS_POWER_SETTING_SET: &'static str = "CABIN_LIGHTS_POWER_SETTING_SET";
pub const PEDESTRAL_LIGHTS_POWER_SETTING_SET: &'static str = "PEDESTRAL_LIGHTS_POWER_SETTING_SET";
pub const GLARESHIELD_LIGHTS_POWER_SETTING_SET: &'static str =
    "GLARESHIELD_LIGHTS_POWER_SETTING_SET";
pub const SET_EXTERNAL_POWER: &'static str = "SET_EXTERNAL_POWER";
pub const TOGGLE_EXTERNAL_POWER: &'static str = "TOGGLE_EXTERNAL_POWER";
