#![allow(dead_code)]

pub const TURBINE_IGNITION_SWITCH_SET: &'static str = "TURBINE_IGNITION_SWITCH_SET";
pub const TURBINE_IGNITION_SWITCH_SET1: &'static str = "TURBINE_IGNITION_SWITCH_SET1";
pub const TURBINE_IGNITION_SWITCH_SET2: &'static str = "TURBINE_IGNITION_SWITCH_SET2";
pub const TURBINE_IGNITION_SWITCH_SET3: &'static str = "TURBINE_IGNITION_SWITCH_SET3";
pub const TURBINE_IGNITION_SWITCH_SET4: &'static str = "TURBINE_IGNITION_SWITCH_SET4";
pub const TURBINE_IGNITION_SWITCH_TOGGLE: &'static str = "TURBINE_IGNITION_SWITCH_TOGGLE";
